from os import environ

FLASK_SECRET = environ.get("FLASK_SECRET")
FLASK_SESSION_TYPE = environ.get("FLASK_SESSION_TYPE")
FLASK_SESSION_REDIS = environ.get("FLASK_SESSION_REDIS")

CELERY_BROKER_URL = environ.get("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = environ.get("CELERY_RESULT_BACKEND")

ELASTIC_SEARCH_HOST = environ.get("ELASTIC_SEARCH_HOST")
ELASTICSEARCH_USERNAME = environ.get("ELASTICSEARCH_USERNAME")
ELASTICSEARCH_PASSWORD = environ.get("ELASTICSEARCH_PASSWORD")

MONGODB_CONNECT_URL = environ.get("MONGODB_CONNECT_URL")
STRIPE_KEY = environ.get("STRIPE_KEY")
STRIPE_WEBHOOK_SECRET = environ.get("STRIPE_WEBHOOK_SECRET")