from os import environ
# flask
FLASK_SECRET = environ.get("FLASK_SECRET")
FLASK_SESSION_TYPE = environ.get("FLASK_SESSION_TYPE")
FLASK_SESSION_REDIS = environ.get("FLASK_SESSION_REDIS")

# celery
CELERY_BROKER_URL = environ.get("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = environ.get("CELERY_RESULT_BACKEND")

# Elastic search
ELASTIC_SEARCH_HOST = environ.get("ELASTIC_SEARCH_HOST")
ELASTICSEARCH_USERNAME = environ.get("ELASTICSEARCH_USERNAME")
ELASTICSEARCH_PASSWORD = environ.get("ELASTICSEARCH_PASSWORD")

# Mongo
MONGODB_CONNECT_URL = environ.get("MONGODB_CONNECT_URL")

# Stripe
STRIPE_KEY = environ.get("STRIPE_KEY")
STRIPE_WEBHOOK_SECRET = environ.get("STRIPE_WEBHOOK_SECRET")

# Digital ocean spaces
DIGITALOCEAN_SPACES_ACCESS_KEY_ID = environ.get("DIGITALOCEAN_SPACES_ACCESS_KEY_ID")
DIGITALOCEAN_SPACES_ACCESS_KEY_SECRET_KEY = environ.get("DIGITALOCEAN_SPACES_ACCESS_KEY_SECRET_KEY")
DIGITALOCEAN_SPACES_ENDPOINT = environ.get("DIGITALOCEAN_SPACES_ENDPOINT")
DIGITALOCEAN_SPACES_REGION = environ.get("DIGITALOCEAN_SPACES_REGION")